import { Injectable } from '@angular/core';
import {InMemoryDbService} from 'angular-in-memory-web-api';

@Injectable({
  providedIn: 'root'
})
export class InMemoryApiService implements InMemoryDbService{

  constructor() { }
  createDb(){
    const Usuarios = [
      {
        "Cedula": 5,
        "Nombre": "Perez",
        "Apellido": "Blankenship",
        "email": "p@p.com",
        "Telefono": "+1 (813) 438-2785",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Estudiante",
        "Usuario": "Blackburn",
        "Contrasena": "Barrett",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 10,
        "Nombre": "Morse",
        "Apellido": "Stout",
        "email": "p@p.com",
        "Telefono": "+1 (839) 546-3418",
        "TipoVehiculo": "Moto",
        "Placa": "NEN942",
        "Perfil": "Profesor",
        "Usuario": "Delaney",
        "Contrasena": "Lang",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 4,
        "Nombre": "Erma",
        "Apellido": "Roth",
        "email": "p@p.com",
        "Telefono": "+1 (913) 514-2150",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Profesor",
        "Usuario": "Latisha",
        "Contrasena": "Wise",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 2,
        "Nombre": "Reeves",
        "Apellido": "Grant",
        "email": "p@p.com",
        "Telefono": "+1 (855) 595-3315",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Estudiante",
        "Usuario": "Eve",
        "Contrasena": "Yates",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 4,
        "Nombre": "Bruce",
        "Apellido": "Conway",
        "email": "p@p.com",
        "Telefono": "+1 (855) 481-2358",
        "TipoVehiculo": "Moto",
        "Placa": "YXR42D",
        "Perfil": "Profesor",
        "Usuario": "Dena",
        "Contrasena": "Zamora",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 4,
        "Nombre": "Vinson",
        "Apellido": "Chapman",
        "email": "p@p.com",
        "Telefono": "+1 (846) 517-3678",
        "TipoVehiculo": "Moto",
        "Placa": "MOE72B",
        "Perfil": "Estudiante",
        "Usuario": "Beth",
        "Contrasena": "Mullins",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 6,
        "Nombre": "Sloan",
        "Apellido": "Burnett",
        "email": "p@p.com",
        "Telefono": "+1 (839) 441-2394",
        "TipoVehiculo": "Moto",
        "Placa": "YXR42D",
        "Perfil": "Estudiante",
        "Usuario": "Brandi",
        "Contrasena": "Forbes",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 1,
        "Nombre": "Fowler",
        "Apellido": "Holmes",
        "email": "p@p.com",
        "Telefono": "+1 (801) 539-2355",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Estudiante",
        "Usuario": "Fitzgerald",
        "Contrasena": "Soto",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 4,
        "Nombre": "Burton",
        "Apellido": "Trevino",
        "email": "p@p.com",
        "Telefono": "+1 (895) 462-3607",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Estudiante",
        "Usuario": "Diana",
        "Contrasena": "Wilcox",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 10,
        "Nombre": "Antonia",
        "Apellido": "Allison",
        "email": "p@p.com",
        "Telefono": "+1 (960) 479-3579",
        "TipoVehiculo": "Moto",
        "Placa": "MOE72B",
        "Perfil": "Profesor",
        "Usuario": "Abby",
        "Contrasena": "Rowland",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 1,
        "Nombre": "Maryellen",
        "Apellido": "Chavez",
        "email": "p@p.com",
        "Telefono": "+1 (855) 446-2272",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Estudiante",
        "Usuario": "Carly",
        "Contrasena": "Mckee",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 6,
        "Nombre": "Randall",
        "Apellido": "Wade",
        "email": "p@p.com",
        "Telefono": "+1 (989) 412-2213",
        "TipoVehiculo": "Carro",
        "Placa": "YXR42D",
        "Perfil": "Profesor",
        "Usuario": "Bean",
        "Contrasena": "Barron",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 10,
        "Nombre": "Mendez",
        "Apellido": "Smith",
        "email": "p@p.com",
        "Telefono": "+1 (857) 425-3553",
        "TipoVehiculo": "Carro",
        "Placa": "YXR42D",
        "Perfil": "Estudiante",
        "Usuario": "Karin",
        "Contrasena": "Patel",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 2,
        "Nombre": "Stout",
        "Apellido": "Hahn",
        "email": "p@p.com",
        "Telefono": "+1 (996) 508-3472",
        "TipoVehiculo": "Moto",
        "Placa": "NEN942",
        "Perfil": "Estudiante",
        "Usuario": "Oliver",
        "Contrasena": "Hood",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 2,
        "Nombre": "Fox",
        "Apellido": "Patterson",
        "email": "p@p.com",
        "Telefono": "+1 (905) 581-3059",
        "TipoVehiculo": "Carro",
        "Placa": "NEN942",
        "Perfil": "Profesor",
        "Usuario": "Golden",
        "Contrasena": "Mays",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 5,
        "Nombre": "Louisa",
        "Apellido": "Oneill",
        "email": "p@p.com",
        "Telefono": "+1 (857) 571-3808",
        "TipoVehiculo": "Moto",
        "Placa": "NEN942",
        "Perfil": "Profesor",
        "Usuario": "Rivas",
        "Contrasena": "Patrick",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 10,
        "Nombre": "Donovan",
        "Apellido": "Sweeney",
        "email": "p@p.com",
        "Telefono": "+1 (911) 437-3012",
        "TipoVehiculo": "Moto",
        "Placa": "MOE72B",
        "Perfil": "Estudiante",
        "Usuario": "Duncan",
        "Contrasena": "Alvarado",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 7,
        "Nombre": "Doris",
        "Apellido": "Deleon",
        "email": "p@p.com",
        "Telefono": "+1 (989) 443-2427",
        "TipoVehiculo": "Carro",
        "Placa": "YXR42D",
        "Perfil": "Estudiante",
        "Usuario": "Maryanne",
        "Contrasena": "Arnold",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 4,
        "Nombre": "Jeanne",
        "Apellido": "Ballard",
        "email": "p@p.com",
        "Telefono": "+1 (911) 477-3577",
        "TipoVehiculo": "Moto",
        "Placa": "YXR42D",
        "Perfil": "Profesor",
        "Usuario": "Gabrielle",
        "Contrasena": "Ross",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      },
      {
        "Cedula": 10,
        "Nombre": "Geneva",
        "Apellido": "Macias",
        "email": "p@p.com",
        "Telefono": "+1 (983) 445-3423",
        "TipoVehiculo": "Moto",
        "Placa": "NEN942",
        "Perfil": "Profesor",
        "Usuario": "Vang",
        "Contrasena": "Bates",
        "Estado": "Activo",
        "TipoDocumento": "CC"
      }
    ]
    return {Usuarios};
  }
}
