//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsParqueadero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id_Pago { get; set; }
        public Nullable<int> Tarifa { get; set; }
        public Nullable<int> Cedula { get; set; }
        public string Fecha { get; set; }
        public string HoraIngreso { get; set; }
        public string Total { get; set; }
        public string EstadoTx { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
